name: Zephyr Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:v0.26.4

    steps:


    - name: Set up Zephyr environment
      run: |
        west init ~/zephyrproject
        cd ~/zephyrproject
        west zephyr-export
        pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt
        echo "List"
        ls
        
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build the project
      run: |
        echo "list"
        ls
        west build --pristine --board nrf52840dongle_nrf52840 --no-sysbuild -- -DNCS_TOOLCHAIN_VERSION=NONE -DBOARD_ROOT= -DCACHED_CONF_FILE=prj.conf

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-hex
        path: build/zephyr/zephyr.hex
