name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.26.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: USB_BLE_HID

      - name: Initialize
        working-directory: USB_BLE_HID
        run: |
          pip3 install --no-cache-dir -U west
          west init -l .
          west update
          echo "Listing files in USB_BLE_HID directory:"
          ls -la
          echo "Listing below folders:"
          cd ..
          ls -la
          echo "Listing files in USB_BLE_HID/zephyr/scripts directory:"
          ls -la zephyr/scripts
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build NRF project
        run: |
          west build --build-dir build --pristine --board nrf52840dongle_nrf52840 --no-sysbuild -- -DNCS_TOOLCHAIN_VERSION=NONE -DBOARD_ROOT= -DCACHED_CONF_FILE=prj.conf
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
