name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/zephyr-build:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Zephyr Setup
        run: |
          pip3 install -U west
          west init -l .
          cd zephyrproject
          west update
          pip3 install -r /zephyr/scripts/requirements-base.txt
      
      - name: Build NRF project
        run: |
          west build --build-dir build --pristine --board nrf52840dongle_nrf52840 --no-sysbuild -- -DNCS_TOOLCHAIN_VERSION=NONE -DBOARD_ROOT= -DCACHED_CONF_FILE=prj.conf
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
