name: Zephyr Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:v0.26.4

    steps:


    - name: Set up Zephyr environment
      run: |
        west init ~/zephyrproject
        cd ~/zephyrproject
        west update
        west zephyr-export
        pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt
        echo "List"
        ls
        
    - name: Checkout repository
      run: |
        ls
        git -C ~/zephyrproject clone https://github.com/malto101/USB_BLE_HID.git
        ls ~/zephyrproject
      
    - name: Build the project
      run: |
        echo "list"
        ls
        cd ~/zephyrproject/ 
        west build -p always -b nrf52840dongle USB_BLE_HID 

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-hex
        path: build/zephyr/zephyr.hex
